spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
  application:
      name: gulimall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 10001
logging:
  level:
    com.guo.gulimall: debug
#alibaba:
#  cloud:
#    access-key: LTAI4G8mcNmnKGh6Rp31C4zs
#    secret-key: VW1x6yo4EUwLs6FVoWhy4eC6jFwbWL
#    oss:
#      endpoint: oss-cn-hangzhou.aliyuncs.com