kind: Deployment
apiVersion: apps/v1
metadata:
  name: gulimall-member-v1
  namespace: gulimall
  labels:
    app: gulimall-member
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-member
      version: v1
  template:
    metadata:
      labels:
        app: gulimall-member
        version: v1
    spec:
      containers:
        - name: gulimall-member
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1000Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: gulimall-member
  namespace: gulimall
  labels:
    app: gulimall-member
spec:
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30006
  selector:
    app: gulimall-member
    version: v1
  type: NodePort
  sessionAffinity: None