server:
  port: 20000
spring:
  application:
    name: gulimall-seckill
  zipkin:
    base-url: http://192.168.56.10:9411 # Zipkin 服务器地址
    discovery-client-enabled: false # 关闭服务发现
    sender:
      type: web # 设置用 http 方式进行传输
  sleuth:
    redis:
      enabled: false
    sampler:
      probability: 1 # 设置抽样采集率为 100%，默认0.1，即 10%
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.56.10
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    virtual-host: /
    host: 192.168.56.10
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.guo.gulimall: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
