spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
    sentinel:
      transport:
        dashboard: localhost:8333
  application:
      name: gulimall-order
  redis:
    host: 192.168.56.10
    port: 6379
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
seata:
  tx-service-group: order_tx_group
  registry:
    nacos:
      server-addr: 192.168.56.10:8848
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 192.168.56.10:8848
      username: nacos
      password: nacos
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: '*'

gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10