#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://115.29.195.125:3306/gulimall_oms
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 115.29.195.125:8848
#  application:
#      name: gulimall-order
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 9000